Feature/networking client queries
PlayPro/CoreProtect pull request #211
Opened 2022-04-24 11:29 UTC by vacla

* Adds response packet
* Adds input packet
* Adds silent messages
* Fixes reload networking

2022-04-26 21:24 UTC, DarkKronicle approved these changes

2022-06-25 23:26 UTC, vacla commented
@Intelli would it be possible to look at this before next Coreprotect release?

2022-06-28 02:22 UTC, Intelli commented
Can you describe what these changes are doing?

What's the use case for silent messages?

2022-06-28 02:45 UTC, vacla commented
@Intelli this is a follow up from the previous networking PR i made, i tagged you in discord with an example for what the input response and response packages are meant for, the silent flag is just so nothing will be sent in chat but it is totally up to the user if nothing will be sent in chat or not since there is an autopage also so the users won't need to go thru every page but that is also optional and wont happen if the user doesnt want it, i can provide you with a jar so you can try it out.

2022-09-09 19:22 UTC, Intelli commented
Please provide the examples here.

Any functionality intended for client-side mods, that can be accomplished in client-side mods, should be left in those mods, rather than being implemented in the plugin.

2022-09-09 20:20 UTC, vacla commented
@Intelli 

![image](https://user-images.githubusercontent.com/10290022/189436363-7761392d-3df3-4bb5-bb19-86af611395dc.png)

the data in the ui is partially provided with the handshake, the actions and the worlds since the client won't know about these directly, all the data if submitted happens over de input channel, this will happen as a format like a command that you would sent as usual, and the popup that you see is the response packet that was sent by coreprotect

2022-09-09 20:27 UTC, vacla commented
There are also examples how to use the networking api in the documentation.

2022-09-09 21:20 UTC, Intelli requested changes

2022-09-09 21:20 UTC, Intelli commented on lang/en.yml
> +LOOKUP_FINISHED: "Lookup Finished"
Please remove unused LOOKUP_FINISHED phrase

2022-09-09 21:20 UTC, Intelli commented on src/main/java/net/coreprotect/command/CommandHandler.java
> +                                    Chat.sendResponse(player, Color.DARK_AQUA + "CoreProtect " + Color.WHITE + "- " + Phrase.build(Phrase.INVALID_INCLUDE, argument), "coreprotect:search", silent);
"coreprotect:search" is not a valid command (coreprotect:lookup)

2022-09-09 21:20 UTC, Intelli commented on src/main/java/net/coreprotect/listener/channel/PluginChannelInputListener.java
> +            Chat.console(exception.toString());
Duplicate exception information?

2022-09-09 21:20 UTC, Intelli commented on src/main/java/net/coreprotect/utility/Chat.java
> +    public static void sendMessageSilent(CommandSender user, String message, boolean silent) {
`sendMessageSilent`, `sendComponentSilent`, and `sendComponentSilent` seem unnecessary.

Can just move the `sendMessageSilent` logic into `sendResponse` for improved clarity.

2022-09-09 21:28 UTC, vacla commented on lang/en.yml
> +LOOKUP_FINISHED: "Lookup Finished"
It is being used here: https://github.com/PlayPro/CoreProtect/pull/211/files#diff-aeeaed8bd7931b9f87f7c7995b43968b15886536833939a5ab1a8ec32fbc8085R1101

2022-09-09 21:31 UTC, Intelli commented on lang/en.yml
> +LOOKUP_FINISHED: "Lookup Finished"
Link just takes me to changed files, but I only see 3 references:
`en`.yml`, `language.java`, and `Phrase.java`

2022-09-09 21:35 UTC, vacla commented on src/main/java/net/coreprotect/utility/Chat.java
> +    public static void sendMessageSilent(CommandSender user, String message, boolean silent) {
`sendMessageSilent`, `sendComponentSilent` and `sendComponentSilent` are all used in `LookupCommand`, these methods are all handled differently.

2022-09-09 21:39 UTC, vacla commented on src/main/java/net/coreprotect/listener/channel/PluginChannelInputListener.java
> +            Chat.console(exception.toString());
Removed Chat.console method call

2022-09-09 21:39 UTC, vacla commented on src/main/java/net/coreprotect/command/CommandHandler.java
> +                                    Chat.sendResponse(player, Color.DARK_AQUA + "CoreProtect " + Color.WHITE + "- " + Phrase.build(Phrase.INVALID_INCLUDE, argument), "coreprotect:search", silent);
Changed it to coreprotect:lookup

2022-09-09 21:40 UTC, vacla commented on lang/en.yml
> +LOOKUP_FINISHED: "Lookup Finished"
Check the LookupCommand class, it doesn't fully show up since it has too many changes to display.

2022-12-12 22:20 UTC, Intelli commented
I think a better way to approach this may be to create separate method(s) from the existing internal chat API. Modifying the [existing methods](https://github.com/PlayPro/CoreProtect/pull/211/files#diff-fb5e9a30f9606f690272a636ebd1cd5b1dad2adc8e189c5baa3c6b23906b2657) is a bit messy, and could create maintainability issues in the future. As well, things like [silencing chat](https://github.com/PlayPro/CoreProtect/pull/211/commits/75c0fd8acc5d4b0da25872550683c8eebe409ced#diff-a0792bef3911c24867485ff0f751d39af5d9030d5c967fd6d5501e977bf4f9b2) could then be a single simple switch within an existing chat method.

Things that can easily be implemented client-side should be left client-side, such as the [task that loops](https://github.com/PlayPro/CoreProtect/pull/211/files#diff-9dbeb2dae16faf0eb2618dcae165d2bd81fa513fa4b82b4cacafebb807dfb9be) through all the pages. The plugin already has server-side functionality for displaying multiple pages of data at once, namely the `rows:` and `/co lookup <page>:<rows>` parameters. The "Lookup Finished" phrase can also be removed, as it isn't something necessary to be displayed during lookups. 

To note, API changes or additions will no longer be pulled until before a major release. Only bug fixes will be pulled into the master branch prior to minor version releases.

2023-01-03 04:16 UTC, vacla commented
@Intelli Would it be fine if i ran the runCommand internally inside CP instead of just letting the player run a command for the networking api?
And the reasons why i don't want to let the player sent the commands themself is:
1. Limited messages per seconds can be sent
2. Commands will be logged in the players chat history
(Copied from #development)

2023-01-03 17:25 UTC, Intelli commented
> @Intelli Would it be fine if i ran the runCommand internally inside CP instead of just letting the player run a command for the networking api? And the reasons why i don't want to let the player sent the commands themself is:
> 
> 1. Limited messages per seconds can be sent
> 2. Commands will be logged in the players chat history
>    (Copied from #development)

1. CoreProtect already has internal command throttling. Triggering the commands internally would still have these throttles, so I doubt you'd see any real-world difference here.
2. CoreProtect is a logging plugin, so if a player runs a command, then it should be logged in that players command history.

2023-03-13 05:11 UTC, closed without merging