Show renamed item names and custom model data when hovering the mouse over the Item
PlayPro/CoreProtect pull request #221
Opened 2022-05-15 08:27 UTC by GreenJon902

When you hover your mouse over an item when inspecting a chest, it will show the custom name of that item and also the customModelData (Only if set to true in config).
![image](https://user-images.githubusercontent.com/37347905/168463485-92bc1ffa-d625-4d1d-80a3-b9e325ab6e80.png)
![image](https://user-images.githubusercontent.com/37347905/168463535-62a835ce-0deb-4a96-95e3-193d7ed9a1c6.png)
![image](https://user-images.githubusercontent.com/37347905/168463546-8685aa69-bcc9-425c-8de0-02d54738e248.png)
If an item does not have any customModelData or does not have a custom name then it will not be shown, if they have neither then no hover dialogue opens!
I did have to modify [PlayerInteractListener.java](https://github.com/GreenJon902/CoreProtect/blob/2242ba8f45ea1c41a0c4125a2c0c73484547bfaf/src/main/java/net/coreprotect/listener/player/PlayerInteractListener.java#L310) to add newlines that don't get sent as their own messages by replacing `"\\n"` with `"\n"` after the string with `"\n"` was split up.

2022-05-15 09:06 UTC, vacla requested changes

2022-05-15 09:06 UTC, vacla commented on src/main/java/net/coreprotect/database/lookup/ChestTransactionLookup.java
> -import java.sql.ResultSet;
Please revert the formatting to how it was previously

2022-05-15 09:06 UTC, vacla commented on src/main/java/net/coreprotect/database/lookup/ChestTransactionLookup.java
> +                //                                                                                                                                          Keep these in case no hover and target is d
Change to a normal comment like on line 123

2022-05-15 09:07 UTC, vacla commented
@GreenJon902 would it be possible to also add this metadata info to the networking?

2022-05-15 14:20 UTC, GreenJon902 commented
@vacla I believe I have fixed the things you asked me to. By networking did you mean PluginChannelListener as I have added the metadata to that. I do not understand what it is or how to test it but it does not throw any errors.

2022-05-15 16:51 UTC, vacla commented
I'm currently making some improvements for future cases

2022-05-15 18:48 UTC, vacla commented
@GreenJon902 since i can't directly make changes to this PR, I made a PR to your branch: https://github.com/GreenJon902/CoreProtect/pull/1

2022-05-15 18:52 UTC, GreenJon902 commented
@vacla I have merged your pull request, thank you for the help!

2022-05-15 18:53 UTC, vacla commented
No worries, I'm a developer myself that implemented the whole Networking and I will use it for my mod called Watson so now it will be able to show that info also.

2022-05-15 18:54 UTC, vacla commented on src/main/java/net/coreprotect/listener/channel/PluginChannelListener.java
> +                    msgOut.writeUTF(additionalItem.getKey());
Woops, i made a fault here, can you change the writeUTF to Chat.console please?

2022-05-15 18:55 UTC, GreenJon902 commented on src/main/java/net/coreprotect/listener/channel/PluginChannelListener.java
> +                    msgOut.writeUTF(additionalItem.getKey());
Both of them or just the first one?

2022-05-15 19:04 UTC, vacla commented on src/main/java/net/coreprotect/listener/channel/PluginChannelListener.java
> +                    msgOut.writeUTF(additionalItem.getKey());
Both at that position since it will already be added above, in the if statement for network debug is just to sent to console.

2022-05-15 19:10 UTC, GreenJon902 commented on src/main/java/net/coreprotect/listener/channel/PluginChannelListener.java
> +                    msgOut.writeUTF(additionalItem.getKey());
Done!

2022-05-15 19:13 UTC, vacla approved these changes

2022-05-29 20:13 UTC, vacla commented on src/main/java/net/coreprotect/database/lookup/ChestTransactionLookup.java
> +                            additionalData.put("enchantments", additionalData.get("enchantments") + name + "-" + itemMeta.getEnchantLevel(enchant) + "|");
i assume this would look like `sharpness-2|mending-1|` ? If so, would it be possible to remove the last `|` at the end?

2022-10-01 19:43 UTC, GreenJon902 commented
The co lookup command can now see the item enchants, custom names, and custom model data (if enabled)!

2022-11-04 01:24 UTC, JHarris12345 commented
Was this added into main core protect? How can I get the version with it in?

2022-11-04 15:07 UTC, GreenJon902 commented
No, I believe it's still waiting to merged into the main release. If you really want this feature then you could probably compile it yourself from my fork of this repository (https://github.com/GreenJon902/CoreProtect).

2022-12-22 02:13 UTC, Intelli commented
Tooltips for item names and enchantments have been implemented here: https://github.com/PlayPro/CoreProtect/commit/5d6fd60d40281f51fbd248dc7099e008de67b862

2022-12-22 02:13 UTC, closed without merging