Update Traditional Chinese translation
PlayPro/CoreProtect pull request #392
Opened 2023-06-23 17:17 UTC by ianiiaannn

2023-06-27 15:13 UTC, flandretw commented
@ianiiaannn
I agree to this translation formatting correction. And can you help me change my name to flandretw? That's my new name, thank you very much.

2023-07-17 23:04 UTC, Intelli commented
The problem with replacing the colon with a separate space (": "), with the "：" character, is that the backend translation processing on the web server will then replace it with an ":" character... but then we'll be missing a space.

So ideally, we should just keep a standard colon. Rest of the changes should be fine though.

2023-07-17 23:06 UTC, Intelli requested changes

2023-07-17 23:06 UTC, Intelli commented on lang/zh-tw.yml
> -CACHE_ERROR: "警告: 驗證快取 {0} 時出現錯誤。"
Colons shouldn't be modified.

2023-07-17 23:06 UTC, Intelli commented on src/main/java/net/coreprotect/language/Phrase.java
> +            output = output.replaceFirst(FULL_WIDTH_SPLIT, FULL_WIDTH_SPLIT + color);
You can keep these changes, for people who wish to run their own modified language files utilizing the FULL_WIDTH_SPLIT (colon) character.

2023-07-19 20:35 UTC, merged