Improvements in performance and logic
PlayPro/CoreProtect pull request #47
Opened 2021-07-17 21:43 UTC by yakovliam

2021-07-17 22:42 UTC, vacla requested changes

2021-07-17 22:42 UTC, vacla commented on src/main/java/net/coreprotect/bukkit/Bukkit_v1_17.java
> +            return adjacent;
Return directly instead

2021-07-17 22:42 UTC, vacla commented on src/main/java/net/coreprotect/bukkit/Bukkit_v1_17.java
> +        else return super.isAttached(block, scanBlock, blockData, scanMin);
Use same format as othet statements

2021-07-17 22:42 UTC, vacla commented on src/main/java/net/coreprotect/command/LookupCommand.java
> +                                String blockdata;
Cant check code but sometimes better to give default  value already

2021-07-17 22:42 UTC, vacla commented on src/main/java/net/coreprotect/command/LookupCommand.java
> +                                                    String dname;
Give default value preferable

2021-07-17 22:42 UTC, vacla commented on src/main/java/net/coreprotect/command/LookupCommand.java
>                                                      String action = "a:block";
For both, preferable add default value

2021-07-17 22:42 UTC, vacla commented on src/main/java/net/coreprotect/command/LookupCommand.java
>                  }
Add for early return

2021-07-17 22:42 UTC, vacla commented on src/main/java/net/coreprotect/command/LookupCommand.java
> -                    return;
Add for early return

2021-07-17 22:42 UTC, vacla commented on src/main/java/net/coreprotect/command/PurgeCommand.java
> +                    PreparedStatement preparedStmt;
Add preferable default value back

2021-07-17 22:42 UTC, vacla commented on src/main/java/net/coreprotect/command/RollbackRestoreCommand.java
> +                int x;
Readd default values back preferable

2021-07-17 22:42 UTC, vacla commented on src/main/java/net/coreprotect/command/StatusCommand.java
> +                        int consumerCount;
Readd preferable default value back

2021-07-17 22:42 UTC, vacla commented on src/main/java/net/coreprotect/command/TabHandler.java
> +                String filter;
Readd preferable default value back

2021-07-17 22:42 UTC, vacla commented on src/main/java/net/coreprotect/command/TeleportCommand.java
> +        if (!location.getWorld().isChunkLoaded(chunkX, chunkZ)) {
Previous one is better check, please revert

2021-07-17 22:42 UTC, vacla commented on src/main/java/net/coreprotect/consumer/Consumer.java
> +        if (!running) {
Previous one is better check, please rever

2021-07-17 22:42 UTC, vacla commented on src/main/java/net/coreprotect/consumer/process/BlockPlaceProcess.java
> +            else BlockPlaceLogger.log(preparedStmt, batchCount, user, block, Util.getBlockId(replaceType), replaceData, blockType, blockData, forceData == 1, meta, newBlockData, replacedBlockData);
Please use same format for the statements

2021-07-17 22:42 UTC, vacla commented on src/main/java/net/coreprotect/database/Rollback.java
Please revert, always make arraylist beforehand

2021-07-17 22:42 UTC, vacla commented on src/main/java/net/coreprotect/listener/block/BlockBreakListener.java
> +        else return BukkitAdapter.ADAPTER.isAttached(block, scanBlock, blockData, scanMin);
Please use same format statements

2021-07-17 22:42 UTC, vacla commented on src/main/java/net/coreprotect/listener/player/InventoryChangeListener.java
>                  onInventoryInteract(player.getName(), inventory, containerState, containerType, inventoryLocation, true);
== false is better check

2021-07-17 22:42 UTC, vacla commented on src/main/java/net/coreprotect/utility/Util.java
> +            else return newItem.isSimilar(oldItem) && newItem.getAmount() > oldItem.getAmount();
Use same format ad other statements

2021-07-17 23:24 UTC, yakovliam commented on src/main/java/net/coreprotect/database/Rollback.java
Can you elaborate? In my opinion, creating a new ArrayList is allocating unused heap space because it's being assigned later anyway.

2021-07-17 23:30 UTC, yakovliam commented on src/main/java/net/coreprotect/listener/player/InventoryChangeListener.java
>                  onInventoryInteract(player.getName(), inventory, containerState, containerType, inventoryLocation, true);
Is this a codestyle choice to match the rest of the project or a personal suggestion?

2021-07-17 23:32 UTC, yakovliam commented on src/main/java/net/coreprotect/listener/block/BlockBreakListener.java
> +        else return BukkitAdapter.ADAPTER.isAttached(block, scanBlock, blockData, scanMin);
This is a good point, fixed.

2021-07-17 23:32 UTC, yakovliam commented on src/main/java/net/coreprotect/bukkit/Bukkit_v1_16.java
> +        else return super.getEntityMeta(entity, info);
This is a good point, fixed everywhere else too.

2021-07-18 05:12 UTC, vacla commented on src/main/java/net/coreprotect/listener/player/InventoryChangeListener.java
>                  onInventoryInteract(player.getName(), inventory, containerState, containerType, inventoryLocation, true);
From work experience, always suggest to do explicit checks

2021-07-18 06:09 UTC, vacla requested changes

2021-07-18 06:09 UTC, vacla commented on src/main/java/net/coreprotect/database/Rollback.java
Remove variable here and do an direct return also

2021-07-18 20:21 UTC, yakovliam commented on src/main/java/net/coreprotect/bukkit/Bukkit_v1_17.java
> -        return true;
It shouldn't, no.

2021-07-18 20:22 UTC, yakovliam commented on src/main/java/net/coreprotect/database/Rollback.java
That would be up to the author since it was initialized there for some purpose. I am just simplifying its initialization.

2021-07-18 20:58 UTC, Intelli requested changes
Added a few comments that apply to all similar changes though the code.

Please also make sure testing has been performed where necessary.

2021-07-18 20:58 UTC, Intelli commented on src/main/java/net/coreprotect/command/RollbackRestoreCommand.java
> +                int x;
I agree, we should keep variables properly initialized

2021-07-18 20:58 UTC, Intelli commented on src/main/java/net/coreprotect/bukkit/Bukkit_v1_16.java
> +        BlockGroup.TRACK_BOTTOM = new HashSet<>(Collections.singletonList(Material.WEEPING_VINES));
Isn’t this just adding an unnecessary inconsistency?

2021-07-18 20:58 UTC, Intelli commented on src/main/java/net/coreprotect/bukkit/Bukkit_v1_17.java
> +            name = "DIRT_PATH";
This isn’t a beneficial forward-looking change.

If additional types are added, a switch is preferable to if/else

2021-07-18 20:58 UTC, Intelli commented on src/main/java/net/coreprotect/command/LookupCommand.java
> -                    return;
Removing this makes the intent unclear.

In general, return statements should be kept.

2021-07-18 20:58 UTC, Intelli commented on src/main/java/net/coreprotect/listener/block/BlockSpreadListener.java
> -            if (cacheData != null && ((Material) cacheData[1]) == type) {
This makes the code less clear.

2021-07-18 20:58 UTC, Intelli commented on src/main/java/net/coreprotect/listener/block/BlockSpreadListener.java
> -                below = null;
On mobile — noting for future review

2021-07-18 22:49 UTC, Intelli commented on src/main/java/net/coreprotect/listener/block/BlockSpreadListener.java
> -                below = null;
Confirmed, removing this is fine.

2021-07-18 22:52 UTC, Intelli commented on src/main/java/net/coreprotect/command/LookupCommand.java
> -                    return;
Checked the code, and this removal is actually fine (doesn't add inconsistencies)

2021-07-18 22:55 UTC, Intelli commented on src/main/java/net/coreprotect/listener/player/InventoryChangeListener.java
>                  onInventoryInteract(player.getName(), inventory, containerState, containerType, inventoryLocation, true);
Either way is fine for me

2021-07-18 23:02 UTC, Intelli commented on src/main/java/net/coreprotect/database/Rollback.java
The list should be left initialized, and `return null;` should be replaced with `return list;` within the method.

2021-07-18 23:56 UTC, yakovliam commented on src/main/java/net/coreprotect/bukkit/Bukkit_v1_16.java
> +        BlockGroup.TRACK_BOTTOM = new HashSet<>(Collections.singletonList(Material.WEEPING_VINES));
singletonList is not backed by an array and just has a reference to that one item. Presumably, it would take less memory and can be significant depending on the number of lists you want to create. If you think it's not a good change, then it can be changed back!

2021-07-19 00:28 UTC, Intelli commented on src/main/java/net/coreprotect/bukkit/Bukkit_v1_16.java
> +        BlockGroup.TRACK_BOTTOM = new HashSet<>(Collections.singletonList(Material.WEEPING_VINES));
As it's just being used for initializing the HashSet, I don't believe there should be a noticeable difference in memory usage either way.

2021-07-27 21:03 UTC, lexikiq commented on src/main/java/net/coreprotect/listener/player/InventoryChangeListener.java
>                  onInventoryInteract(player.getName(), inventory, containerState, containerType, inventoryLocation, true);
er, why not `enderChest ? Material.ENDER_CHEST : null` to avoid the inversion in the first place :P

2021-08-02 21:19 UTC, yakovliam commented
Unable to to maintain this PR until merge/closing, so I am closing now.

2021-08-02 21:19 UTC, closed without merging