Update de.yml
PlayPro/CoreProtect pull request #518
Opened 2024-03-24 12:40 UTC by DasPotata

some changes for the lang file

2024-03-24 21:45 UTC, Lovinoes commented
looks good to me 👍
approved

2024-05-24 02:45 UTC, Intelli commented
HELP_INSPECT_1 - HELP_INSPECT_7 looks like they’re being made too lengthy. Each phrase should be a single line in the chat output (I.e. brevity is intentional).

Please be sure to test the changes with the plugin, to ensure there are no issues with chat formatting.

2024-07-23 11:30 UTC, dlsf requested changes
This PR is definitely a huge improvement, although I would personally make a couple of adjustments. I tweaked some translations so they fit on one line.

2024-07-23 11:30 UTC, dlsf commented on lang/de.yml
> +HELP_INSPECT_7: "Tipp: Du kannst einfach \"/co i\" verwenden, um schnelleren Zugriff zu erhalten."
Shortened the translation & made sure it was short enough to fit on one line in-game. I had to make the fifth line reference the fourth one because it's already very close to maximum length and there's no way to make this work in German, lol. Furthermore, I removed the periods at the end of each line because I couldn't make HELP_INSPECT_3 work with them, but I think this should be fine.

```suggestion
HELP_INSPECT_1: "Mit dem Inspector kannst du Folgendes tun:"
HELP_INSPECT_2: "Linksklicke einen Block, um zu sehen, wer ihn platziert hat"
HELP_INSPECT_3: "Rechtsklick auf einen Block zeigt Änderungen an Nachbarn an"
HELP_INSPECT_4: "Platziere einen Block, um Änderungen an seinem Ort zu sehen"
HELP_INSPECT_5: "So kann man auch Änderungen an Flüssigkeiten etc. sehen"
HELP_INSPECT_6: "Rechtsklicke Türen, Truhen, etc., um Zugriffe zu sehen"
HELP_INSPECT_7: "Tipp: Benutze \"/co i\" für schnelleren Zugriff"
```

2024-07-23 11:30 UTC, dlsf commented on lang/de.yml
> +HELP_PARAMS_7: "Schließe Blöcke/Benutzer von dem {Lookup|Rollback|Restore} aus."
Shortened this so it fits on one line, although I somewhat prefer the old translations

```suggestion
HELP_PARAMS_1: "Führe einen {Lookup|Rollback|Restore} durch."
HELP_PARAMS_2: "Spieler, für die der {Lookup|Rollback|Restore} gemacht werden soll."
HELP_PARAMS_3: "Zeitspanne, für die der {Lookup|Rollback|Restore} gemacht werden soll."
HELP_PARAMS_4: "Radius, für den der {Lookup|Rollback|Restore} gemacht werden soll."
HELP_PARAMS_5: "Aktion, für die der {Lookup|Rollback|Restore} gemacht werden soll."
HELP_PARAMS_6: "Schließe Blöcke/Entitäten in den {Lookup|Rollback|Restore} ein."
HELP_PARAMS_7: "Schließe Blöcke/Benutzer von dem {Lookup|Rollback|Restore} aus."
```

2024-07-23 11:30 UTC, dlsf commented on lang/de.yml
> +LOOKUP_ITEM: "{0} {aufgehoben|abgeworfen} {1} {2}."
I think "weggeworfen" is a more natural translation for "dropped" in this context

```suggestion
LOOKUP_ITEM: "{0} {aufgehoben|weggeworfen} {1} {2}."
```

2024-07-23 11:30 UTC, dlsf commented on lang/de.yml
> +LOOKUP_TIME: "Vor {0}"
Personally I think it looks better in-game if it's lowercase like in English, although it doesn't really matter

```suggestion
LOOKUP_TIME: "vor {0}"
```

2024-07-23 19:05 UTC, merged