Japanese translation patch
PlayPro/CoreProtect pull request #672
Opened 2024-11-08 16:52 UTC by shotadft

Fixed some translations that were still incomplete as of the last issue (#660).
However, please note that they may be incomplete.

2024-11-08 16:55 UTC, shotadft commented
My guess is that such mistranslations occurred in large numbers because English and Japanese grammar are very different.

2024-11-12 20:16 UTC, shotadft reviewed
Partial correction. This should be mostly ok.

2024-11-13 16:56 UTC, waxsd100 requested changes
気になったところをコメントしました。
全ては見ていません。

I commented on what I was interested in.
I didn't see all of them.

2024-11-13 16:56 UTC, waxsd100 commented on lang/ja.yml
> +NO_DATA_LOCATION: "ここで{データ|入れ替え|相互作用|メッセージ}は見つかりませんでした。"
```suggestion
NO_DATA_LOCATION: "{データ|トランザクション|相互作用|メッセージ}は見つかりませんでした。"
```

データに関する語句で、トランザクションは入れ替えなどのニュアンスでは使われていません。
ACID特性などの処理方式の方の単語で使われているので
トランザクションはそのままが良いと思う

The term is used in the sense of data, and transactions are not used in the sense of replacement or other nuances.
The term is used to describe ACID characteristics and other processing methods.
Transaction is better used as it is.

参考: https://swri.jp/glossary/%E3%83%88%E3%83%A9%E3%83%B3%E3%82%B6%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3

---

https://github.com/PlayPro/CoreProtect/blob/master/lang/en.yml#L133

を見ると否定形としての「No」が使われているので
最後が「見つかりません」なら先頭に文字は必要ありません。

shows that “No” is used as a negative form, so the first letter is not necessary if the last is “Not found.
If the last word is “not found”, the first letter is not necessary.

機械翻訳では、「No」を「No.（番号）」と誤訳することがよくある。
In machine translation, there is often a mistranslation of “No” into “No. (number)”.

2024-11-13 16:56 UTC, waxsd100 commented on lang/ja.yml
> +HELP_TELEPORT: "テレポートします。それ以上でもそれ以下でもありません。"
[HELP_TELEPORT: "Teleport to a location."](https://github.com/PlayPro/CoreProtect/blob/master/lang/en.yml#L77)
だから「テレポートします。」もしくは「この場所にテレポートします。」ぐらいになるかと思います。

So, “I'm teleporting.” Or “I will teleport to this location.” I think it would be about the same.

「それ以上でもそれ以下でもありません。」は言葉の意味がよくわかりません。
The words “no more and no less” don't make sense.

2024-11-13 16:56 UTC, waxsd100 commented on lang/ja.yml
> +HELP_PARAMS_2: "{検索|ロールバック|復元}をする際に特定ユーザーが起こした行動を巻き戻します。"
検索か復元の時でも、ユーザの行動をロールバックする。という意味になる。
It is misinterpreted to mean that the user's actions are rolled back, even when they are “retrieved” or “restored.”

```suggestion
HELP_PARAMS_2: "{検索|ロールバック|復元}するユーザを指定します。"
```

2024-11-13 16:56 UTC, waxsd100 commented on lang/ja.yml
> +LOOKUP_LOGIN: "{0}の{入力|出力}がログに記録されます。"
「ログイン or ログアウト」に関するメッセージだから「入力 or 出力」はおかしい。
The "input or output" is wrong because the message is about "login or logout".

2024-11-13 16:56 UTC, waxsd100 commented on lang/ja.yml
> +CONSUMER_TOGGLED: "消費者の待機列処理が{一時停止|再開}されました。"
Consumer とqueue とかの単語はストリーミング処理の言葉としてよく使われています。
この単語は一般的には、カタカナで表記されることが一般的です。
Words like consumer and queue are often used to describe streaming processes.
These words are generally written in katakana.

なので消費者や待機列に訳さなくてもよいです。
So there is no need to replace it with "消費者"or "待機列".


参考:
https://docs.oracle.com/ja-jp/iaas/Content/Streaming/Tasks/using_consumer_groups.htm
https://blog.trocco.io/glossary/streaming-data

2024-11-13 16:56 UTC, waxsd100 commented on lang/ja.yml
> +CONSUMER_TOGGLED: "消費者の待機列処理が{一時停止|再開}されました。"
https://github.com/PlayPro/CoreProtect/pull/672/files#diff-ee8bbe2e987b34d6f6b79d09f1a5317d2fab8a46e0d079e0e56a3471d6342991R177

2024-11-13 16:56 UTC, waxsd100 commented on lang/ja.yml
> +DIRT_BLOCK: "あなたの下に土ブロックを置きました。"
[nits]
https://github.com/PlayPro/CoreProtect/blob/master/lang/en.yml#L27

を見ると足元に仮ブロックを設置する的な意味で使われているから、土ブロックって明言するのは良いのかちょっと悩む
I'm a little worried about whether it's a good idea to explicitly say “dirt block” or not, since it is used in the sense of installing temporary blocks underfoot when you look at the

2024-11-14 08:58 UTC, shotadft commented on lang/ja.yml
> +DATABASE_LOCKED_1: "データベースがロックされています。最大15秒時間を頂く場合がございます。"
15秒時間は完全にタイポですねw
修正しときます。ありがと。

2024-11-14 09:01 UTC, shotadft commented on lang/ja.yml
> +CONSUMER_TOGGLED: "消費者の待機列処理が{一時停止|再開}されました。"
消費者は翻訳修正前の段階で翻訳されてたので修正しときますね

2024-11-14 09:10 UTC, shotadft reviewed
[waxsd100](https://github.com/waxsd100)さん、修正提案ありがとうございます！
Thanks to [waxsd100](https://github.com/waxsd100) for the revised proposal!

2024-11-14 09:11 UTC, shotadft commented on lang/ja.yml
> +DIRT_BLOCK: "あなたの下に土ブロックを置きました。"
修正しときました！

2024-11-14 17:00 UTC, waxsd100 reviewed
ごめん何個か見逃してた。
他にもトランザクションと入れ替えとか色々混ざってる気がするがそこはスルーします。
(気が向いたときにゲーム内確認してこっちで直します)

修正した内容はLGTM

2024-11-14 17:00 UTC, waxsd100 commented on lang/ja.yml
> +PREVIEW_TRANSACTION: "{コンテナ|在庫}の入れ替えがプレビューできません"
```suggestion
PREVIEW_TRANSACTION: "{コンテナ|在庫}}のトランザクションをプレビューすることはできません"
```
ごめん、見逃した。
Sorry, I missed it.

2024-11-14 17:00 UTC, waxsd100 commented on lang/ja.yml
> +ROLLBACK_CHUNKS_FOUND: "変更する{0}{チャンク|チャンク}が見つかりました。"
自然な日本語にするなら
If you want to use natural Japanese
```suggestion
ROLLBACK_CHUNKS_FOUND: "{0}{チャンク|チャンク}の変更が見つかりました。"
```

2024-11-14 17:00 UTC, waxsd100 commented on lang/ja.yml
> +PURGE_MINIMUM_TIME: "パージできるのは、より古いデータのみです。({0}{日|時間})"
```suggestion
PURGE_MINIMUM_TIME: "パージできるのは、({0}{日|時間})より古いデータのみです。"
```

`パージできるのは、1時間より古いデータのみです。` 
みたいになるはず（そうすると期間を表すので日間のほうが良いかも)

`Only data older than 1 hour can be purged. ` 
should look something like this (then it might be better to use days since it represents a period of time).

2024-11-14 17:00 UTC, waxsd100 commented on lang/ja.yml
> +ROLLBACK_CHUNKS_MODIFIED: "{0}/{1}{チャンク|チャンク} 変更"
```suggestion
ROLLBACK_CHUNKS_MODIFIED: "変更中 {0}/{1}{チャンク|チャンク}"
```

「変更中 2/5チャンク」 みたいな表記になったほうが自然と思う
I think it would be more natural to use something like “changing 2/5 chunks”

2024-11-14 17:00 UTC, waxsd100 commented on lang/ja.yml
> +PURGE_MINIMUM_TIME: "パージできるのは、より古いデータのみです。({0}{日|時間})"
そうするとこっちも
Then we'll get this one too.

https://github.com/PlayPro/CoreProtect/pull/672/files#diff-ee8bbe2e987b34d6f6b79d09f1a5317d2fab8a46e0d079e0e56a3471d6342991R185-R189

日間、週間、分間などの期間時間にしたほうが良いかもしれない
Might be better to make it time period time, such as days, weeks, minutes, etc.

2024-11-14 17:00 UTC, waxsd100 commented on lang/ja.yml
> +TIME_WEEKS: "{0}{週|週}"
> 日間、週間、分間などの期間時間にしたほうが良いかもしれない
> Might be better to make it time period time, such as days, weeks, minutes, etc.

2024-11-14 17:00 UTC, waxsd100 commented on lang/ja.yml
> +SIGN_HEADER: "メッセージに署名"
署名ではなく看板の意味だと思う
I don't think he meant the sign, but the sign.

どんな感じが正しいかは
ゲーム内で確認しないとわからないので、ここは今は直さなくても良いただのコメントです。  
I'm not sure what it looks like is correct.
I'll have to check in-game to be sure, so this is just a comment that doesn't need to be fixed now.  

https://minecraft.fandom.com/wiki/Sign

2024-11-14 17:00 UTC, waxsd100 commented on lang/ja.yml
> +STATUS_CONSUMER: "消費者: {0}{アイテム|アイテム達}のキューを待っています"
変更漏れ
omission of change

```suggestion
STATUS_CONSUMER: "{0}{アイテム|アイテム達}のキューを処理中"
```

消費中はコンシューム中と言ったりしますが専門用語すぎるので処理中に直してみました。
While consuming, it is also called consume, but that is too technical a term, so I changed it to process.

2024-11-14 17:16 UTC, waxsd100 approved these changes
LGTM

2024-11-14 17:19 UTC, waxsd100 commented
@Intelli please review

---

This pull request includes various updates and improvements to the Japanese localization file `lang/ja.yml`. The changes primarily focus on improving the accuracy and clarity of translations, correcting grammatical errors, and enhancing consistency across the file.

Key updates and improvements:

* **Translation Accuracy and Clarity:**
  * Updated the translation for "AMOUNT_ENTITY" to "{0}体の{エンティティ|エンティティ}" to improve clarity.
  * Corrected "COMMAND_NOT_FOUND" to "コマンド \"{0}\" は見つかりません。" for better grammatical accuracy.
  * Modified "ENABLE_SUCCESS" to "{0} が有効化されました。" to ensure proper verb usage.

* **Consistency Enhancements:**
  * Standardized the translation for "LOOKUP_BLOCK" to "{0}が{1}を{配置|破壊}した。" to maintain uniformity in action descriptions.
  * Updated "ROLLBACK_STARTED" to "{ロールバック|復元|プレビュー}が「{0}」で開始されました。" for consistent use of quotation marks.

* **Grammatical Corrections:**
  * Corrected "DATABASE_LOCKED_1" to "データベースがロックされています。最大15秒間かかる場合があります。" for better readability.
  * Fixed "HELP_LOOKUP_COMMAND" to "ブロックデータを検索します。" to improve sentence structure.
  * Adjusted "INVALID_USERNAME" to "\"{0}\"は無効なユーザー名です。" to ensure proper punctuation.

2024-11-15 21:32 UTC, shotadft commented
@Intelli 
<hr>
取り敢えずある程度のギャップは修正したので一度、これで完成としたいです。
マージとレビューをお願いします。
EN: I've fixed a few gaps for now, so I'll mark this as complete.
Please merge and review.

2024-11-16 14:14 UTC, shotadft reviewed
@Intelli 
<hr>
取り敢えずある程度のギャップは修正したので一度、これで完成としたいです。
マージとレビューをお願いします。<br>
EN: I've fixed a few gaps for now, so I'll mark this as complete.
Please merge and review.

2024-11-22 11:19 UTC, shotadft commented
I put up this pull request two weeks ago. When will it be merged?

2024-11-24 14:39 UTC, shotadft commented on lang/ja.yml
> +TIME_WEEKS: "{0}{週|週}"
コミットしときます

2024-11-24 14:41 UTC, shotadft commented on lang/ja.yml
> +SIGN_HEADER: "メッセージに署名"
一応変更しときますね、一応。

2024-12-07 02:25 UTC, shotadft commented
A month has passed since then, and still?

2024-12-09 04:07 UTC, shotadft commented
@waxsd100 取り敢えずのレビューをお願いします。

2024-12-11 05:21 UTC, shotadft commented
![Screenshot_20241211-142020~2](https://github.com/user-attachments/assets/90e4e114-ad1d-4d55-932d-8891cf82e916)
I'm sad

2024-12-30 11:42 UTC, shotadft commented
@waxsd100 Review pls.

2025-01-31 16:24 UTC, shotadft commented
**on Nov 9, 2024**

2025-03-04 10:26 UTC, closed without merging